RED = ("changed", "wbg")
RED_HIGHLIGHT = ("changed", "wfg")
ORANGE = ("srcpair", "wbg")
BLUE = ("srcdrct", "wbg")
SKYBLUE = ("clbg", "wbg")
SKYBLUE_HIGHLIGHT = ("clbg", "wfg")
PURPLE = ("srcannot", "wbg")
GRAY = ("verbfg", "wbg")
BLACK = ("subbg", "wbg")
DARK_RED = ("srcid", "wbg")
DARK_RED_HIGHLIGHT = ("srcid", "wfg")
GREEN = ("srccmnt", "wbg")
WHITE = ("verbfg", "wbg")
YELLOW = ("srcnum", "wbg")
LIME = ("wfg", "wbg")
LIME_HIGHLIGHT = ("wbg", "wfg")

def red(content): return colorize(RED, content)
def yellow(content): return colorize(YELLOW, content)
def orange(content): return colorize(ORANGE, content)
def blue(content): return colorize(BLUE, content)
def purple(content): return colorize(PURPLE, content)
def gray(content): return colorize(GRAY, content)
def skyblue(content): return colorize(SKYBLUE, content)
def dark_red(content): return colorize(DARK_RED, content)
def green(content): return colorize(GREEN, content)
def white(content): return colorize(WHITE, content)
def lime(content): return colorize(LIME, content)
def lime_highlight(content): return colorize(LIME_HIGHLIGHT, content)
def skyblue_highlight(content): return colorize(SKYBLUE_HIGHLIGHT, content)
def red_highlight(content): return colorize(RED_HIGHLIGHT, content)
def dark_red_highlight(content): return colorize(DARK_RED_HIGHLIGHT, content)
def colorize(col, content): return "<col fg=\"{}\" bg=\"{}\">{}</col>".format(col[0], col[1], content)
